- name: Update and upgrade apt packages
  become: True
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Ensure obsolete docker versions are not installed
  package:
    name:
      - docker
      - docker-engine
    state: absent

- name: Ensure docker apt dependencies are present
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - python3-pip
      - curl
      - software-properties-common
    state: present

- name: Ensure python dependencies for docker are present
  pip:
    name: docker
    executable: pip3

- name: Add docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: Add docker apt key to repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic nightly
    state: present
    update_cache: true

- name: Install docker
  package:
    name: docker-ce
    state: present
  notify: restart docker



- name: Ensure docker users are added to the docker group
  user:
    name: "{{ item.name }}"
    groups: docker
    append: true
  with_items: "{{ users }}"
