name: Build Docker
on: [push]
jobs:
  build_nodejs_related_things:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: refs/heads/master
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Npm Install
      run: npm install
    - name: Npm Test
      run: npm test
    - name: Npm Pack
      run: npm pack

  build_docker_related_things:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: refs/heads/master
    - name: Build docker image
      run: docker build --tag ${GITHUB_REPOSITORY#*/} ${PWD}
    - name: List files
      run: ls -lsah
    - name: Docker save image
      run: docker save -o {GITHUB_SHA}.tar ${GITHUB_REPOSITORY#*/}
    - name: Ansible Deploy
      env:
        ANSIBLE_HOST_KEY_CHECKING: False
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: ansible-playbook --extra-vars="
        github_sha=${GITHUB_SHA}
        github_repository_name=${GITHUB_REPOSITORY#*/}
        ansible_user=${SSH_USER}
        ansible_password=${SSH_PASSWORD}" -i env/digitalocean deploy.yml

