name: Build Docker
on: [push]
jobs:
  build_docker_related_things:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: refs/heads/master
    - uses: actions/setup-node
      with: 12.x
    - name: Npm Install
      run: npm install
    - npm: Npm Pack
      run: npm pack

